Repository intuit/hooks, pull requests merged in 2021-03, with the labels that each got.

#5 Publish to Gradle Plugin Portal
  build.gradle.kts
Labels: patch

#6 update docs for gradle plugin portal
  README.md
  gradle-plugin/README.md
Labels: documentation

#8 Hooks with type parameters
  compiler-plugin/src/main/kotlin/com/intuit/hooks/plugin/CodeGeneration.kt
  compiler-plugin/src/main/kotlin/com/intuit/hooks/plugin/Hooks.kt
  compiler-plugin/src/test/kotlin/com/intuit/hooks/plugin/HookTest.kt
Labels: minor

#7 Update to use Typed Quotes
  compiler-plugin/src/main/kotlin/com/intuit/hooks/plugin/Hooks.kt
Labels: patch

#12 Setup Auto for Canary and Next
  .circleci/config.yml
Labels: internal, skip-release
